export DOTFILES_ROOT=$(dirname "$(dirname "$(readlink -f "$0")")")

# XDG Base Directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_RUNTIME_DIR="/run/user/$UID"

## aws-cli
export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME"/aws/credentials
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME"/aws/config

## docker
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker

## lesshst
export LESSHISTFILE="$XDG_STATE_HOME"/less/history

## rbenv
export RBENV_ROOT="$XDG_DATA_HOME"/rbenv

## volta
export VOLTA_HOME="$XDG_DATA_HOME"/volta

## wget
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"

## wine
export WINEPREFIX="$XDG_DATA_HOME"/wine

## npm
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc

## matplotlib
export MPLCONFIGDIR="$XDG_CONFIG_HOME/matplotlib"
