# Environment variables
export PATH="$VOLTA_HOME/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH" # uv
export GIT_ROOT=$(dirname $DOTFILES_ROOT)

# Application settings
eval "$(zoxide init zsh)" # zoxide

# history settings
export HISTFILE="$XDG_STATE_HOME"/zsh/history
HISTSIZE=100000
SAVEHIST=1000000
setopt HIST_IGNORE_DUPS
setopt inc_append_history
setopt share_history

# alias
## replace commands
alias cd="z"
alias ls="eza -F --group-directories-first --icons -s=extension --color=always"
alias l="ls"
alias la="ls -a"
alias ll="la -l --git --no-user --time-style=long-iso"
alias llf="ls -al --no-user --no-permissions --no-time --no-filesize"
alias cp="cp -r"
alias cat="bat"
alias rm="trash"
alias du="dua"
alias dui="dua interactive"

## shortcuts
alias ..="cd ../"
alias v="nvim"
alias vz="v $ZDOTDIR/.zshrc"
alias vze="v $ZDOTDIR/.zshenv"
alias sz="source $ZDOTDIR/.zshrc"
alias mdc='(){mkdir $1 && cd $1}'
alias c="code ."
alias o="open ."

## git
alias gl="ghq list"
alias gs="git switch"

## uv
alias ur="uv run"
alias ui="uv pip install"
alias ua="uv add"

## my apps
alias llm-webui="$GIT_ROOT/llm-webui/entrypoint.sh"

# import modules
for file in "$DOTFILES_ROOT"/modules/*; do
  [ -f "$file" ] && source "$file"
done

# Enable the custom application commands
export PATH="$DOTFILES_ROOT/applications:$PATH"

## others
alias path="echo $PATH | tr : '\n'"
alias wtr='() {curl ja.wttr.in/"${1:-Tokyo}"}'
alias kusa='() {curl "https://github-contributions-api.deno.dev/{$1}.term"}'
