# Environment variables
export PATH="$VOLTA_HOME/bin:$PATH"
export PATH="`npm bin -g`:$PATH"
export PATH="$HOME/.local/bin:$PATH" # uv
export GIT_ROOT=$(dirname $DOTFILES_ROOT)

# zsh settings
autoload -U promptinit; promptinit # pure prompt
prompt pure

eval "$(zoxide init zsh)" # zoxide

autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' # 小文字でも大文字にマッチさせる
zstyle ':completion:*:default' menu select=1 # Tabや矢印で選択できるようにする
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME"/zsh/zcompcache
compinit -d "$XDG_CACHE_HOME"/zsh/zcompdump-"$ZSH_VERSION"

zinit light zsh-users/zsh-completions # コマンド補完
zinit light zsh-users/zsh-syntax-highlighting # シンタックスハイライト
zinit light zsh-users/zsh-autosuggestions # 入力補完

export HISTFILE="$XDG_STATE_HOME"/zsh/history
HISTSIZE=100000
SAVEHIST=1000000
setopt HIST_IGNORE_DUPS # 同じコマンドが続いた場合履歴に残さない
setopt inc_append_history # 他のzshと履歴を共有
setopt share_history
setopt AUTO_CD # パスを直接入力してもcdする
setopt AUTO_PARAM_KEYS # 環境変数を補完

# zinit light zdharma/history-search-multi-word # 履歴検索
# bindkey '^R' history-incremental-search-backward # Ctrl+Hで履歴検索

# alias
## replace commands
alias cd="z"
alias ls="eza -F --group-directories-first --icons -s=extension --color=always"
alias l="ls"
alias la="ls -a"
alias ll="la -l --git --no-user --time-style=long-iso"
alias llf="ls -al --no-user --no-permissions --no-time --no-filesize"
alias cp="cp -r"
alias cat="bat"
alias rm="trash"
alias du="dua"
alias dui="dua interactive"

## shortcuts
alias ..="cd ../"
alias v="nvim"
alias vz="v $ZDOTDIR/.zshrc"
alias vze="v $ZDOTDIR/.zshenv"
alias sz="source $ZDOTDIR/.zshrc"
alias mdc='(){mkdir $1 && cd $1}'
alias c="code ."
alias o="open ."

## git
alias gl="ghq list"
alias gs="git switch"

## uv
alias ur="uv run"
alias ui="uv pip install"

# import modules
for file in "$DOTFILES_ROOT"/modules/*; do
  [ -f "$file" ] && source "$file"
done

# Enable the custom application commands
export PATH="$DOTFILES_ROOT/applications:$PATH"

## others
alias path="echo $PATH | tr : '\n'"
alias wtr='() {curl ja.wttr.in/"${1:-Tokyo}"}'
alias kusa='() {curl "https://github-contributions-api.deno.dev/{$1}.term"}'
