# Environment variables
export PATH="$HOME/.local/bin:$PATH" # uv
export GIT_ROOT=$(dirname $DOTFILES_ROOT)

# Application settings
eval "$(zoxide init zsh)" # zoxide
eval "$(atuin init zsh --disable-up-arrow)" # atuin
eval "$(mise activate zsh)" # mise
. "$HOME/.local/share/cargo/env" # rust


if [ -n "${GHOSTTY_RESOURCES_DIR}" ]; then
  source "${GHOSTTY_RESOURCES_DIR}/shell-integration/zsh/ghostty-integration" # Ghostty
fi

# history settings
export HISTFILE="$XDG_STATE_HOME"/zsh/history
HISTSIZE=100000
SAVEHIST=1000000
setopt HIST_IGNORE_DUPS
setopt inc_append_history
setopt share_history
setopt EXTENDED_HISTORY

# zsh settings
autoload -Uz compinit && compinit
zstyle ':completion:*:default' menu select=1 # Tabや矢印で選択できるようにする
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' # 小文字でも大文字にマッチさせる
zstyle ':completion:*' expand 'yes' # 環境変数を展開
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME"/zsh/zcompcache
compinit -d "$XDG_CACHE_HOME"/zsh/zcompdump-"$ZSH_VERSION"
setopt AUTO_CD # パスを直接入力してもcdする
setopt AUTO_PARAM_KEYS # 環境変数を補完
ZSH_AUTOSUGGEST_STRATEGY=(history completion) # 補完候補の拡張

## zinit settings
source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

zinit light zsh-users/zsh-syntax-highlighting # シンタックスハイライト
zinit light zsh-users/zsh-autosuggestions # 入力補完

# pure prompt
zinit ice pick"async.zsh" src"pure.zsh"
zinit light sindresorhus/pure
PURE_PROMPT_SYMBOL='🐤'

# alias
## replace commands
alias cd="z"
alias ls="eza -F --group-directories-first --icons -s=extension --color=always"
alias l="ls"
alias la="ls -a"
alias ll="la -l --git --no-user --time-style=long-iso"
alias cp="cp -r"
alias cat="bat"
alias rm="trash"
alias du="dua"
alias dui="dua interactive"

## shortcuts
alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"
alias mdc='(){mkdir $1 && cd $1}'
alias c="code ."
alias o="open ."
alias free="cd $HOME/workspace/free"

v() {
  if [ "$#" -eq 0 ]; then
    nvim .
  else
    nvim "$@"
  fi
}

## my apps
alias llmweb="$HOME/workspace/llm-webui/entrypoint.sh"

## git
alias gs="git switch"

## uv
alias ui="uv pip install"
alias ua="uv add"

# import modules
for file in "$DOTFILES_ROOT"/modules/*; do
  [ -f "$file" ] && source "$file"
done

# Enable the custom application commands
export PATH="$DOTFILES_ROOT/applications:$PATH"

## others
alias path='echo $PATH | tr : "\n"'
alias wtr='() {curl ja.wttr.in/"${1:-Tokyo}"}'
alias kusa='() {curl "https://github-contributions-api.deno.dev/{$1}.term"}'
